"""Add description to Club

Revision ID: 306ff63a771d
Revises: 7299fe4b5246
Create Date: 2025-01-22 11:00:18.185109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306ff63a771d'
down_revision = '7299fe4b5246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
