"""Add member_limit to Club

Revision ID: 590759bf465a
Revises: 306ff63a771d
Create Date: 2025-01-22 12:08:06.875827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590759bf465a'
down_revision = '306ff63a771d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('member_limit')

    # ### end Alembic commands ###
